create table app.price (
    fullprice int,
    saleprice int,
    GCD int
)

INSERT INTO APP.PRICE VALUES (27, 9, 0);
INSERT INTO APP.PRICE VALUES (36, 4, 0);
INSERT INTO APP.PRICE VALUES (45, 9, 0);
INSERT INTO APP.PRICE VALUES (15, 5, 0);
INSERT INTO APP.PRICE VALUES (27, 0, 0);
INSERT INTO APP.PRICE VALUES (9, 0, 0);
INSERT INTO APP.PRICE VALUES (80, 10, 0);
INSERT INTO APP.PRICE VALUES (21, 7, 0);
INSERT INTO APP.PRICE VALUES (54, 9, 0);
INSERT INTO APP.PRICE VALUES (120,12, 0);

SELECT * FROM APP.PRICE;